### PR TITLE
Unity 5 Compatibility fix

### PR DESCRIPTION
**Pull request by alaa-eddine**
managed to get it working with Unity 5 :)
Here is the fixed version.

I used #Unity_5 conditional compilation switch so the old code is kept as is for older version.

### CODE REVIEW

**Comment by mythgarr** [comment]
I'm no longer actively maintaining the Spriter2Unity project and haven't done much to keep current on Unity changes in general, but I'm sure many users will appreciate your changes.
I can't verify whether or not your changes work, but it appears that the line
{{BindingFlags bindingFlags}}
shows up twice in AnimationCurveUtils.cs. It looks like this method is public as of Unity 5, so that line is only needed for older versions.

**Comment by alaa-eddine** [comment]
Sorry for this mistake :) 
I fixed it in the last commit

**Comment by AlexanderYoshi** [comment]
I wanted to verity that his changes work correctly, but that line 192 in AnimationCurveUtils.cs is not needed.

            //Use reflection to get the internal method
            BindingFlags bindingFlags = BindingFlags.Static | BindingFlags.NonPublic;

**Comment by alaa-eddine** [comment]
The line is needed for Unity < 5.

I'll post another PR

**Comment by Dharengo** [comment]
Are you sure it is? The line doesn't actually do anything. The variable actually is never used anywhere.

**Comment by AlexanderYoshi** [comment]
He's correct - the 4.3 version uses it as a parameter.

**Comment by alaa-eddine** [comment]
just made a PR to fix it :)

**Comment by Dharengo** [comment]
Then why isn't it in side a directive?

**Comment by Dharengo** [comment]
Ah I've seen your fix. I've tried to merge your fork into mine but apparently I ran into some kind of conflict. Idk how to resolve conflicts so I just changed my fork manually.

**Pull request merged**
